# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

import("UITest")
import("Android")

platform :android do

lane :pr_on_develop do
    unit_test
end

lane :ui_tests do |options|
    matrix_api = options[:matrix_api]
    matrix_emulator = options[:matrix_emulator]
    matrix_test_suite = options[:matrix_test_suite]
    matrix_env = options[:conf]
    begin
        ui_test(matrix_env: matrix_env, matrix_api: matrix_api, matrix_emulator: matrix_emulator, matrix_test_suite: matrix_test_suite)
    end
end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
